image: python:3.7

services:
  - redis:latest

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "${LOCAL_SSH_PRIVATE_KEY}" | ssh-add -
  - echo "${SSH_PRIVATE_KEY}" | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ls -la ~/.ssh
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

stages:
  - tests
  - staging
  - deploy

format:
  stage: tests
  script:
    - echo "static_analysis not implemented"

phpunit:
  stage: tests
  script:
    - echo "unit test not implemented"

beta:
  stage: staging
  dependencies:
    - format
    - phpunit
  script:
    - pip3 install Fabric3==1.13.1.post1
    - fab stage deploy
  only:
    - develop

deploy:
  stage: deploy
  dependencies:
    - beta
  script:
    - echo "master deploy not implemented"
    - ls -la
  only:
    - master
