stages:
  - tests
  - staging
  - deploy

format:
  stage: tests
  image: circleci/php:7.4
  script:
    - ls -la
    - pwd
    - composer global require "squizlabs/php_codesniffer=*"
    - cd $(composer global config bin-dir --absolute)
    - phpcs -v --extensions=php --standard=PSR2 ~/app/src

phpunit:
  stage: tests
  image: circleci/php:7.4
  script:
    - cd app
    - curl --location --output /usr/local/bin/phpunit https://phar.phpunit.de/phpunit.phar
    - chmod +x /usr/local/bin/phpunit
    - phpunit --configuration phpunit_myapp.xml

beta:
  stage: staging
  image: python:3.7
  dependencies:
    - format
    - phpunit
  script:
    - mkdir -p ~/.ssh
    - 'which ssh-agent || ( apt update && apt install openssh-client )'
    - eval $(ssh-agent -s)
    - echo "${LOCAL_SSH_PRIVATE_KEY}" | ssh-add -
    - echo "${SSH_PRIVATE_KEY}" | ssh-add -
    - touch  ~/.ssh/kerf-1.pem
    - echo "${SSH_PRIVATE_KEY}" > ~/.ssh/kerf-1.pem
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - pip3 install Fabric3==1.13.1.post1
    - fab stage deploy
  only:
    - develop

deploy:
  stage: deploy
  image: python:3.7
  dependencies:
    - beta
  script:
    - echo "master deploy not implemented"
    - ls -la
  only:
    - master
