before_script:
  - mkdir -p ~/.ssh
  - 'which ssh-agent || ( apk add --update --no-cache openssh-client)'
  - eval $(ssh-agent -s)
  - echo "${LOCAL_SSH_PRIVATE_KEY}" | ssh-add -
  - echo "${SSH_PRIVATE_KEY}" | ssh-add -
  - touch  ~/.ssh/kerf-1.pem
  - echo "${SSH_PRIVATE_KEY}" > ~/.ssh/kerf-1.pem
  - chmod 700 ~/.ssh
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

stages:
  - tests
  - staging
  - deploy

format:
  stage: tests
  image: php:7.4-fpm-alpine
  script:
    - apk add --update --no-cache zip unzip
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar install
    - composer require overtrue/phplint --dev -vvv
    - ./vendor/bin/phplint ./ --exclude=vendor

phpunit:
  stage: tests
  image: python:3.7-alpine
  script:
    - echo "unit test not implemented"

beta:
  stage: staging
  image: python:3.7
  dependencies:
    - format
    - phpunit
  script:
    - pip3 install Fabric3==1.13.1.post1
    - fab stage deploy
  only:
    - develop

deploy:
  stage: deploy
  image: python:3.7
  dependencies:
    - beta
  script:
    - echo "master deploy not implemented"
    - ls -la
  only:
    - master
