image: python:3.7

services:
  - redis:latest

before_script:
  # install ssh-agent
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  # run ssh-agent
  - eval $(ssh-agent -s)
  # add ssh key stored in SSH_PRIVATE_KEY variable to the agent stores
  - echo "${LOCAL_SSH_PRIVATE_KEY}" | ssh-add -
  - mkdir ~/.ssh
  - cat "$LOCAL_SSH_PRIVATE_KEY" ~/.ssh/kerf-1.pem
  - chmod 644 ~/.ssh/kerf-1.pem
  # disable host key checking (NOTE: makes you susceptible to man-in-the-middle attacks)
  # WARNING: use only in docker container, if you use it with shell you will overwrite your user's ssh config
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

stages:
  - format
  - tests
  - deploy_stage
  - deploy

format:
  stage: format
  script:
    - echo "static_analysis not implemented"

tests:
  stage: tests
  script:
    - echo "unit test not implemented"

deploy_stage:
  stage: deploy_stage
  dependencies:
    - tests
    - format
  script:
    - pip3 install Fabric3==1.13.1.post1
    - fab develop deploy
  only:
    - develop

deploy:
  stage: deploy
  script:
    - echo "master deploy not implemented"
    - ls -la
  only:
    - master
