stages:
  - tests
  - staging
  - deploy

format:
  stage: tests
  image: composer:latest
  script:
    - DIR=$(pwd)
    - composer global require "squizlabs/php_codesniffer=*"
    - composer global require "overtrue/phplint=*"
    - cd $(composer global config bin-dir --absolute)
    - ./phpcs -v --extensions=php --standard=PSR2 $DIR/app/src
    - ./phplint  $DIR/app/src --exclude=vendor

phpunit:
  stage: tests
  image: composer:latest
  script: #check if it is necessary full composer install o make it global
    - touch app/.env
    - echo "APP_ENV=$APP_ENV" >> app/.env
    - echo "APP_SECRET=$APP_SECRET" >> app/.env
    - composer install -d app
    - ./app/vendor/bin/phpunit app/tests --testdox

beta:
  stage: staging
  image: python:3.7
  dependencies:
    - format
    - phpunit
  script:
    - mkdir -p ~/.ssh
    - 'which ssh-agent || ( apt update && apt install openssh-client )'
    - eval $(ssh-agent -s)
    - echo "${LOCAL_SSH_PRIVATE_KEY}" | ssh-add -
    - echo "${SSH_PRIVATE_KEY}" | ssh-add -
    - touch  ~/.ssh/kerf-1.pem
    - echo "${SSH_PRIVATE_KEY}" > ~/.ssh/kerf-1.pem
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - pip3 install Fabric3==1.13.1.post1
    - fab stage deploy
  only:
    - develop

deploy:
  stage: deploy
  image: python:3.7
  dependencies:
    - beta
  script:
    - echo "master deploy not implemented"
    - ls -la
  only:
    - master
