version: "3.0"

services:
  nginx:
    image: enrikerf/nginx:latest
    depends_on:
      - php-fpm
    ports:
      - 80:80
      - 9009:9009
    volumes:
      - ./app:/var/www/app
  php-fpm:
    image: enrikerf/php-fpm-xdebug:latest
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/app